
language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo pip install cpp-coveralls --use-mirrors
  - sudo apt-get install -qq pkg-config tcl-dev

script:
  - autoreconf -if
  - ./configure --enable-gcov
  - make
  - make test

after_success:
  - coveralls --exclude lib --exclude tests
